var locationData = [
    {
        "name"       : "Lone Tree Station",
        "url"        : "lone_tree_station",
        "set"        : "valleyBase",
        "setCardNum" : 2,
        "isPivotal"  : true,
        "x"          : 766,
        "y"          : 644,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Ranger Station",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "White Sky",
        "url"        : "white_sky/",
        "set"        : "valleyBase",
        "setCardNum" : 1,
        "isPivotal"  : true,
        "x"          : 1446,
        "y"          : 853,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Northern Outpost",
        "url"        : "northern_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 3,
        "isPivotal"  : true,
        "x"          : 1696,
        "y"          : 178,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Spire",
        "url"        : "spire",
        "set"        : "valleyBase",
        "setCardNum" : 9,
        "isPivotal"  : true,
        "x"          : 1279,
        "y"          : 1536,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Branch",
        "url"        : "branch",
        "set"        : "valleyBase",
        "setCardNum" : 15,
        "isPivotal"  : true,
        "x"          : 1952,
        "y"          : 1717,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Trail",
        "trait4"     : "Ascent",
        "trait5"     : null
    },
    {
        "name"       : "The Fractured Wall",
        "url"        : "fractured_wall",
        "set"        : "valleyBase",
        "setCardNum" : 12,
        "isPivotal"  : true,
        "x"          : 2344,
        "y"          : 1086,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ruin",
        "trait3"     : "Water",
        "trait4"     : "Ascent",
        "trait5"     : null
    },
    {
        "name"       : "Meadow",
        "url"        : "meadow/",
        "set"        : "valleyBase",
        "setCardNum" : 21,
        "isPivotal"  : true,
        "x"          : 1049,
        "y"          : 2481,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Field",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Marsh of Rebirth",
        "url"        : "marsh_of_rebirth/",
        "set"        : "valleyBase",
        "setCardNum" : 32,
        "isPivotal"  : true,
        "x"          : 1921,
        "y"          : 3054,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Tumbledown",
        "url"        : "tumbledown",
        "set"        : "valleyBase",
        "setCardNum" : 37,
        "isPivotal"  : true,
        "x"          : 1289,
        "y"          : 3794,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Mountain",
        "trait3"     : "Water",
        "trait4"     : "Trail",
        "trait5"     : null
    },
    {
        "name"       : "Atrox Mountain",
        "url"        : "atrox_mountain",
        "set"        : "valleyBase",
        "setCardNum" : 4,
        "isPivotal"  : false,
        "x"          : 1213,
        "y"          : 284,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Golden Shore",
        "url"        : "golden_shore/",
        "set"        : "valleyBase",
        "setCardNum" : 5,
        "isPivotal"  : false,
        "x"          : 1583,
        "y"          : 448,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mount Nim",
        "url"        : "mount_nim",
        "set"        : "valleyBase",
        "setCardNum" : 6,
        "isPivotal"  : false,
        "x"          : 2076,
        "y"          : 718,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Boulder Field",
        "url"        : "boulder_field",
        "set"        : "valleyBase",
        "setCardNum" : 7,
        "isPivotal"  : false,
        "x"          : 947,
        "y"          : 1005,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Ancestor's Grove",
        "url"        : "ancestors_grove",
        "set"        : "valleyBase",
        "setCardNum" : 8,
        "isPivotal"  : false,
        "x"          : 415,
        "y"          : 1148,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Kobo's Market",
        "url"        : "kobos_market/",
        "set"        : "valleyBase",
        "setCardNum" : 10,
        "isPivotal"  : false,
        "x"          : 695,
        "y"          : 1427,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Philosopher's Garden",
        "url"        : "the_philosophers_garden/",
        "set"        : "valleyBase",
        "setCardNum" : 13,
        "isPivotal"  : false,
        "x"          : 1787,
        "y"          : 1376,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The High Basin",
        "url"        : "the_high_basin",
        "set"        : "valleyBase",
        "setCardNum" : 14,
        "isPivotal"  : false,
        "x"          : 2234,
        "y"          : 1520,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Plummet",
        "url"        : "the_plummet/",
        "set"        : "valleyBase",
        "setCardNum" : 18,
        "isPivotal"  : false,
        "x"          : 205,
        "y"          : 1790,
        "presence"   : 3,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Crossroads Station",
        "url"        : "crossroads_station",
        "set"        : "valleyBase",
        "setCardNum" : 23,
        "isPivotal"  : false,
        "x"          : 1589,
        "y"          : 1745,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Furrow",
        "url"        : "the_furrow",
        "set"        : "valleyBase",
        "setCardNum" : 16,
        "isPivotal"  : false,
        "x"          : 2548,
        "y"          : 1747,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Biological Outpost",
        "url"        : "biological_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 17,
        "isPivotal"  : false,
        "x"          : 2023,
        "y"          : 2055,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Headwaters Station",
        "url"        : "headwaters_station/",
        "set"        : "valleyBase",
        "setCardNum" : 20,
        "isPivotal"  : false,
        "x"          : 679,
        "y"          : 1728,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Greenbriar Knoll",
        "url"        : "greenbriar_knoll/",
        "set"        : "valleyBase",
        "setCardNum" : 19,
        "isPivotal"  : false,
        "x"          : 1078,
        "y"          : 2007,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Ruin",
        "trait3"     : "Trail",
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Concordant Ziggurats",
        "url"        : "the_concordant_ziggurats",
        "set"        : "valleyBase",
        "setCardNum" : 22,
        "isPivotal"  : false,
        "x"          : 466,
        "y"          : 2484,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Stoneweaver Bridge",
        "url"        : "stoneweaver_bridge",
        "set"        : "valleyBase",
        "setCardNum" : 11,
        "isPivotal"  : false,
        "x"          : 1565,
        "y"          : 2495,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mound of the Navigator",
        "url"        : "mound_of_the_navigator",
        "set"        : "valleyBase",
        "setCardNum" : 26,
        "isPivotal"  : false,
        "x"          : 1946,
        "y"          : 2435,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Terravore",
        "url"        : "terravore/",
        "set"        : "valleyBase",
        "setCardNum" : 27,
        "isPivotal"  : false,
        "x"          : 2387,
        "y"          : 2171,
        "presence"   : 3,
        "trait1"     : "Biomeld",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Greenbridge",
        "url"        : "the_greenbridge",
        "set"        : "valleyBase",
        "setCardNum" : 28,
        "isPivotal"  : false,
        "x"          : 2138,
        "y"          : 2735,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Michael's Bog",
        "url"        : "michaels_bog",
        "set"        : "valleyBase",
        "setCardNum" : 29,
        "isPivotal"  : false,
        "x"          : 1915,
        "y"          : 2758,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cypress Citadel",
        "url"        : "the_cypress_citadel",
        "set"        : "valleyBase",
        "setCardNum" : 30,
        "isPivotal"  : false,
        "x"          : 2183,
        "y"          : 2941,
        "presence"   : 3,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Frowning Gate",
        "url"        : "the_frowning_gate",
        "set"        : "valleyBase",
        "setCardNum" : 31,
        "isPivotal"  : false,
        "x"          : 1712,
        "y"          : 3131,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Sunken Outpost",
        "url"        : "sunken_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 33,
        "isPivotal"  : false,
        "x"          : 2095,
        "y"          : 3250,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Archaeological Outpost",
        "url"        : "archaeological_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 25,
        "isPivotal"  : false,
        "x"          : 538,
        "y"          : 3035,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Rings of the Moon",
        "url"        : "rings_of_the_moon",
        "set"        : "valleyBase",
        "setCardNum" : 24,
        "isPivotal"  : false,
        "x"          : 854,
        "y"          : 2937,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Alluvial Ruins",
        "url"        : "the_alluvial_ruins",
        "set"        : "valleyBase",
        "setCardNum" : 34,
        "isPivotal"  : false,
        "x"          : 1170,
        "y"          : 3257,
        "presence"   : 2,
        "trait1"     : "Ruin",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Bowl of the Sun",
        "url"        : "bowl_of_the_sun",
        "set"        : "valleyBase",
        "setCardNum" : 35,
        "isPivotal"  : false,
        "x"          : 1536,
        "y"          : 3365,
        "presence"   : 1,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Watcher's Rock",
        "url"        : "watchers_rock",
        "set"        : "valleyBase",
        "setCardNum" : 36,
        "isPivotal"  : false,
        "x"          : 765,
        "y"          : 3763,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Chimney",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 1302,
        "y"          : 849,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Severed Artery",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 537,
        "y"          : 3371,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Branching Artery",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 1277,
        "y"          : 3203,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Terminal Artery",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 2033,
        "y"          : 3256,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Mycelial Conclave",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 1751,
        "y"          : 4067,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Verdant Sphere",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 1003,
        "y"          : 5406,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Arboretum of Memory",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 2102,
        "y"          : 5542,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cage",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : true,
        "x"          : 1245,
        "y"          : 6739,
        "presence"   : null,
        "trait1"     : "Pivotal",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Oasis of Sunlight",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 1989,
        "y"          : 989,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Drenching Chamber",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 385,
        "y"          : 2030,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Desert of Endless Night",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 888,
        "y"          : 2464,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Orlin's Vault",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 1529,
        "y"          : 2338,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Scuttler Network",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 2050,
        "y"          : 1933,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Silent Dormitories",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 1053,
        "y"          : 3921,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Cerulean Curtain",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 505,
        "y"          : 4347,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Cistern",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 587,
        "y"          : 4954,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Carbonforged Maze",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 1877,
        "y"          : 4877,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Inverted Forest",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 459,
        "y"          : 5555,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "The Rootway",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 585,
        "y"          : 6070,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    },
    {
        "name"       : "Talpid's Squeeze",
        "url"        : null,
        "set"        : "legacyArcology",
        "setCardNum" : null,
        "isPivotal"  : false,
        "x"          : 1851,
        "y"          : 6015,
        "presence"   : null,
        "trait1"     : null,
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null,
        "trait5"     : null
    }
];