var locationData = [
    {
        "name"       : "Lone Tree Station",
        "url"        : "lone_tree_station",
        "set"        : "valleyBase",
        "setCardNum" : 2,
        "isPivotal"  : true,
        "x"          : 747,
        "y"          : 624,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Ranger Station",
        "trait4"     : null
    },
    {
        "name"       : "White Sky",
        "url"        : "white_sky/",
        "set"        : "valleyBase",
        "setCardNum" : 1,
        "isPivotal"  : true,
        "x"          : 1436,
        "y"          : 835,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null
    },
    {
        "name"       : "Northern Outpost",
        "url"        : "northern_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 3,
        "isPivotal"  : true,
        "x"          : 1692,
        "y"          : 152,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Spire",
        "url"        : "spire",
        "set"        : "valleyBase",
        "setCardNum" : 9,
        "isPivotal"  : true,
        "x"          : 1267,
        "y"          : 1528,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Branch",
        "url"        : "branch",
        "set"        : "valleyBase",
        "setCardNum" : 15,
        "isPivotal"  : true,
        "x"          : 1952,
        "y"          : 1714,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Forest",
        "trait3"     : "Trail",
        "trait4"     : "Ascent"
    },
    {
        "name"       : "The Fractured Wall",
        "url"        : "fractured_wall",
        "set"        : "valleyBase",
        "setCardNum" : 12,
        "isPivotal"  : true,
        "x"          : 2348,
        "y"          : 1074,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Ruin",
        "trait3"     : "Water",
        "trait4"     : "Ascent"
    },
    {
        "name"       : "Meadow",
        "url"        : "meadow/",
        "set"        : "valleyBase",
        "setCardNum" : 21,
        "isPivotal"  : true,
        "x"          : 1035,
        "y"          : 2487,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Field",
        "trait3"     : "Trail",
        "trait4"     : null
    },
    {
        "name"       : "Marsh of Rebirth",
        "url"        : "marsh_of_rebirth/",
        "set"        : "valleyBase",
        "setCardNum" : 32,
        "isPivotal"  : true,
        "x"          : 1920,
        "y"          : 3070,
        "presence"   : 2,
        "trait1"     : "Pivotal",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Tumbledown",
        "url"        : "tumbledown",
        "set"        : "valleyBase",
        "setCardNum" : 37,
        "isPivotal"  : true,
        "x"          : 1278,
        "y"          : 3820,
        "presence"   : 1,
        "trait1"     : "Pivotal",
        "trait2"     : "Mountain",
        "trait3"     : "Water",
        "trait4"     : "Trail"
    },
    {
        "name"       : "Atrox Mountain",
        "url"        : "atrox_mountain",
        "set"        : "valleyBase",
        "setCardNum" : 4,
        "isPivotal"  : false,
        "x"          : 1200,
        "y"          : 259,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Golden Shore",
        "url"        : "golden_shore/",
        "set"        : "valleyBase",
        "setCardNum" : 5,
        "isPivotal"  : false,
        "x"          : 1577,
        "y"          : 425,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Mount Nim",
        "url"        : "mount_nim",
        "set"        : "valleyBase",
        "setCardNum" : 6,
        "isPivotal"  : false,
        "x"          : 2077,
        "y"          : 699,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Boulder Field",
        "url"        : "boulder_field",
        "set"        : "valleyBase",
        "setCardNum" : 7,
        "isPivotal"  : false,
        "x"          : 932,
        "y"          : 991,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Ancestor's Grove",
        "url"        : "ancestors_grove",
        "set"        : "valleyBase",
        "setCardNum" : 8,
        "isPivotal"  : false,
        "x"          : 391,
        "y"          : 1135,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Kobo's Market",
        "url"        : "kobos_market/",
        "set"        : "valleyBase",
        "setCardNum" : 10,
        "isPivotal"  : false,
        "x"          : 676,
        "y"          : 1417,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The Philosopher's Garden",
        "url"        : "the_philosophers_garden/",
        "set"        : "valleyBase",
        "setCardNum" : 13,
        "isPivotal"  : false,
        "x"          : 1783,
        "y"          : 1366,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The High Basin",
        "url"        : "the_high_basin",
        "set"        : "valleyBase",
        "setCardNum" : 14,
        "isPivotal"  : false,
        "x"          : 2236,
        "y"          : 1512,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : "Trail",
        "trait4"     : null
    },
    {
        "name"       : "The Plummet",
        "url"        : "the_plummet/",
        "set"        : "valleyBase",
        "setCardNum" : 18,
        "isPivotal"  : false,
        "x"          : 179,
        "y"          : 1785,
        "presence"   : 3,
        "trait1"     : "Mountain",
        "trait2"     : "Ascent",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Crossroads Station",
        "url"        : "crossroads_station",
        "set"        : "valleyBase",
        "setCardNum" : 23,
        "isPivotal"  : false,
        "x"          : 1582,
        "y"          : 1738,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The Furrow",
        "url"        : "the_furrow",
        "set"        : "valleyBase",
        "setCardNum" : 16,
        "isPivotal"  : false,
        "x"          : 2554,
        "y"          : 1741,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Biological Outpost",
        "url"        : "biological_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 17,
        "isPivotal"  : false,
        "x"          : 2022,
        "y"          : 2054,
        "presence"   : 1,
        "trait1"     : "Forest",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Headwaters Station",
        "url"        : "headwaters_station/",
        "set"        : "valleyBase",
        "setCardNum" : 20,
        "isPivotal"  : false,
        "x"          : 661,
        "y"          : 1723,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Greenbriar Knoll",
        "url"        : "greenbriar_knoll/",
        "set"        : "valleyBase",
        "setCardNum" : 19,
        "isPivotal"  : false,
        "x"          : 1065,
        "y"          : 2005,
        "presence"   : 1,
        "trait1"     : "Field",
        "trait2"     : "Ruin",
        "trait3"     : "Trail",
        "trait4"     : null
    },
    {
        "name"       : "The Concordant Ziggurats",
        "url"        : "the_concordant_ziggurats",
        "set"        : "valleyBase",
        "setCardNum" : 22,
        "isPivotal"  : false,
        "x"          : 444,
        "y"          : 2488,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Stoneweaver Bridge",
        "url"        : "stoneweaver_bridge",
        "set"        : "valleyBase",
        "setCardNum" : 11,
        "isPivotal"  : false,
        "x"          : 1560,
        "y"          : 2500,
        "presence"   : 1,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Mound of the Navigator",
        "url"        : "mound_of_the_navigator",
        "set"        : "valleyBase",
        "setCardNum" : 26,
        "isPivotal"  : false,
        "x"          : 1945,
        "y"          : 2439,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Terravore",
        "url"        : "terravore/",
        "set"        : "valleyBase",
        "setCardNum" : 27,
        "isPivotal"  : false,
        "x"          : 2392,
        "y"          : 2172,
        "presence"   : 3,
        "trait1"     : "Biomeld",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The Greenbridge",
        "url"        : "the_greenbridge",
        "set"        : "valleyBase",
        "setCardNum" : 28,
        "isPivotal"  : false,
        "x"          : 2139,
        "y"          : 2744,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Michael's Bog",
        "url"        : "michaels_bog",
        "set"        : "valleyBase",
        "setCardNum" : 29,
        "isPivotal"  : false,
        "x"          : 1914,
        "y"          : 2768,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The Cypress Citadel",
        "url"        : "the_cypress_citadel",
        "set"        : "valleyBase",
        "setCardNum" : 30,
        "isPivotal"  : false,
        "x"          : 2185,
        "y"          : 2951,
        "presence"   : 3,
        "trait1"     : "Forest",
        "trait2"     : "Water",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "The Frowning Gate",
        "url"        : "the_frowning_gate",
        "set"        : "valleyBase",
        "setCardNum" : 31,
        "isPivotal"  : false,
        "x"          : 1708,
        "y"          : 3145,
        "presence"   : 3,
        "trait1"     : "Water",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Sunken Outpost",
        "url"        : "sunken_outpost",
        "set"        : "valleyBase",
        "setCardNum" : 33,
        "isPivotal"  : false,
        "x"          : 2097,
        "y"          : 3267,
        "presence"   : 2,
        "trait1"     : "Water",
        "trait2"     : "Ruin",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Archaeological Outpost",
        "url"        : "archaeological_outpost/",
        "set"        : "valleyBase",
        "setCardNum" : 25,
        "isPivotal"  : false,
        "x"          : 517,
        "y"          : 3047,
        "presence"   : 1,
        "trait1"     : "Trail",
        "trait2"     : "Ranger Station",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Rings of the Moon",
        "url"        : "rings_of_the_moon",
        "set"        : "valleyBase",
        "setCardNum" : 24,
        "isPivotal"  : false,
        "x"          : 837,
        "y"          : 2949,
        "presence"   : 1,
        "trait1"     : "Ruin",
        "trait2"     : null,
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Alluvial Ruins",
        "url"        : "the_alluvial_ruins",
        "set"        : "valleyBase",
        "setCardNum" : 34,
        "isPivotal"  : false,
        "x"          : 1158,
        "y"          : 3274,
        "presence"   : 2,
        "trait1"     : "Ruin",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Bowl of the Sun",
        "url"        : "bowl_of_the_sun",
        "set"        : "valleyBase",
        "setCardNum" : 35,
        "isPivotal"  : false,
        "x"          : 1529,
        "y"          : 3383,
        "presence"   : 1,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    },
    {
        "name"       : "Watcher's Rock",
        "url"        : "watchers_rock",
        "set"        : "valleyBase",
        "setCardNum" : 36,
        "isPivotal"  : false,
        "x"          : 747,
        "y"          : 3787,
        "presence"   : 2,
        "trait1"     : "Mountain",
        "trait2"     : "Trail",
        "trait3"     : null,
        "trait4"     : null
    }
];